### ISSUE TITLE
Falcon 6.35 Helm installation issue in GKE 

### ISSUE THREAD

**Issue by christidis** [CrowdStrike/falcon-helm#105]
I have already Falcon deployed on GKE using `6.33.0` Falcon Sensor & `1.6.2` Helm Chart version without issues.

I am trying to upgrade to `6.35.0` using Helm chart version `1.11.0` (which according to the readme is compatible).

I downloaded Ubuntu latest `6.35` deb from https://falcon.crowdstrike.com/hosts/sensor-downloads
Then I built the image. Tagged it and pushed it to my repo

```
git clone git@github.com:CrowdStrike/Dockerfiles.git Crowdstrike-Dockerfiles
cd Crowdstrike-Dockerfiles
docker build --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg VCS_REF=$(git rev-parse --short HEAD) --build-arg FALCON_PKG=falcon-sensor_6.35.0-13207_amd64.deb -f Dockerfile.ubuntu -t falcon-sensor:6.35.0 .

docker tag falcon-sensor:6.35.0 us-central1-docker.pkg.dev/my-artifact/docker-registry/crowdstrike/falcon-sensor:ubuntu-6.35.0
docker push us-central1-docker.pkg.dev/my-artifact/docker-registry/crowdstrike/falcon-sensor:ubuntu-6.35.0
```

and deployed it via Helm
```
$ helm upgrade --install falcon-helm crowdstrike/falcon-sensor -n falcon-system --set falcon.cid="$FALCON_CID" --set node.image.repository="us-central1-docker.pkg.dev/my-artifact/docker-registry/crowdstrike/falcon-sensor" --set node.image.tag="ubuntu-6.35.0" --version 1.11.0 --create-namespace
```

The init containers `init-falconstore` fail in the daemonset with the following error
```
0s          Warning   Failed             pod/falcon-helm-falcon-sensor-n9vfp   Error: failed to start container "init-falconstore": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: mkdir /opt/CrowdStrike: read-only file system: unknown
```

It seems that I cannot deploy 6.35 in GKE with `1.7.0`+.
I have also tried the same process using the Dockerfile.debian file with no luck.
I have also tried removing the `mkdir -p` command from the daemonset, again no luck.

The OS of my GKE nodes is the default Container-Optimized OS with Docker ( cos ). 
https://github.com/CrowdStrike/falcon-helm/tree/1.11.0/helm-charts/falcon-sensor#kubernetes-cluster-compatability

**Comment by redhatrises** [comment]
Hello, starting with sensor version 6.35 and helm chart version 1.7.0+, the supported version of the sensor can only be downloaded from registry.crowdstrike.com. Building from the dockerfiles will no longer work.

**Comment by JSchuchman** [comment]
@redhatrises I'm in the same situation. But I have tried sensor version `6.44.14108`, `6.41.13804`, and `6.39.13601`, and all versions still have the same error with helm chart version `1.17.6`. The OS of my GKE nodes is also the default Container-Optimized OS with Docker ( cos ). It appears the gke node hostpath mounts are all read-only, so I have been unable to create the falconstore file. The only work around I have gotten to work is doing the following:
- remove the hostpath mount, and use an empty dir
- update the init container to run falconctl as unpriviliged to create the falconstore file (I have to run the init container as unprivileged, otherwise falconctl fails to find/read/write /opt/Crowdstrike/falconstore)
- Update the run command of the main container to only start the falcon-sensor, and not run falconctl
