### ISSUE TITLE
Falcon Sensor Container Installation

### ISSUE THREAD

**Issue by briannd81** [CrowdStrike/falcon-helm#11]
It appears that the falcon sensor container installation requires privileged mode. Are there any recommendations out there on what security contexts (pod security policy) can be used to put some constraints on the container? Understood it needs to interact directly with the kernel, but does it really need unrestricted access to host?

**Comment by redhatrises** [comment]
> It appears that the falcon sensor container installation requires privileged mode. Are there any recommendations out there on what security contexts (pod security policy) can be used to put some constraints on the container? 

Completely unsupported for a falcon kernel-mode sensor at this point in time.

> Understood it needs to interact directly with the kernel, but does it really need unrestricted access to host?

Yes, it does as it has to appear native to the node and cannot be restricted by namespaces, etc. Otherwise, node protection doesn't work. This assumes that you are creating a the falcon sensor packages (.rpm, .deb, .pkg, .exe, etc.) in a custom container and not the Crowdstrike Falcon Container `.tar` which currently isn't supported at the moment with this Helm chart.  

How much do you care about your node's security? Further, what is the difference between an rpm and a privileged container in this case?

**Comment by briannd81** [comment]
Do we lose any features or capabilities when running Falcon as a container (Helm) vs host (.rpm)?

**Comment by redhatrises** [comment]
Helm is also one Kubernetes-native way of deploying to a cluster. The other is through a Kubernetes Operator. There are also many container-native operating systems that no longer allow customization through package installation and only allow containers.

**Comment by redhatrises** [comment]
As the conversation has appeared to die down on this, I am going to close this. Feel free to reopen if needed... or better yet, create a discussion for questions like these, and then, use the tickets for enhancements and bugs.
