### ISSUE TITLE
AWS EKS 1.31 Support

### ISSUE THREAD

**Issue by ujjwalsoni1903** [CrowdStrike/falcon-helm#339]
Hello , 

Is falcon-sensor 1.29.1 supported on  EKS 1.30 & EKS 1.31 ?

**Comment by redhatrises** [comment]
Assuming you are talking about the node sensor, support is based on the operating system and not the EKS versions as we are deploying standard K8s daemonsets. I would verify your node OSes are supported since that is what will determine sensor support. In general unless K8s specifically makes breaking changes to daemonsets, all verison of supported versions of K8s by the vendors are supported.

**Comment by ujjwalsoni1903** [comment]
Thank you for the support.

I am referring to Falcon as the node sensor. Currently, our nodes in EKS are running Amazon Linux 2, and in future versions, they will be running Amazon Linux 2023.

As suggested, if support is based on the OS, then everything should be good.
